name: auris-server

services:

  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: auris-nacos
    ports:
      - "8848:8848"  # HTTP API（控制台、旧版客户端）
      - "9848:9848"  # gRPC（Nacos 2.x 客户端主要通信方式，注册发现用的就是这个）
    environment:
      MODE: standalone
    volumes:
      - nacos-data:/home/nacos/data

  mysql:
    image: mysql:8.0
    container_name: auris-mysql
    ports:
      - "3306:3306"  # 暴露给宿主机
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auris # 自动创建数据库
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: auris-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  nacos-data:
  mysql-data:
  redis-data:
